[theme]
primaryColor = "#234B3B"
backgroundColor = "#F7F5EF"
secondaryBackgroundColor = "#E7EDE1"
textColor = "#293B33"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
enableStaticServing = true
